CC=g++
CFLAGS=-Wall -g -I/Library/Frameworks/SDL.framework/Headers
FRAMEWORKS=-framework SDL -framework Cocoa -framework SDL_image -framework SDL_ttf

all:
	$(CC) $(CFLAGS) $(FRAMEWORKS) *.cpp *.m
